# Generated by Django 3.1.4 on 2021-01-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
