# Generated by Django 3.1.4 on 2021-01-10 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210110_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sname',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
