# Generated by Django 3.1.4 on 2021-01-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20210111_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='sname',
            new_name='slug',
        ),
    ]
