# Generated by Django 3.1.4 on 2021-01-11 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210110_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='datex',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
