# Generated by Django 3.1.4 on 2021-01-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_expense_datex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='datex',
            new_name='date',
        ),
    ]
